import { Clock3, ShoppingBasket, Sparkles, X } from "lucide-react";
import QtyStepper from "./QtyStepper";

function CartDrawer({ open, onClose, cart, products, onAdd, onRemove, onCheckout }) {
  const items = Object.entries(cart).filter(([, quantity]) => quantity > 0);
  const total = items.reduce((sum, [id, quantity]) => { const product = products.find((item) => item.id === Number(id)); return sum + (product ? product.price * quantity : 0); }, 0);
  return <div className={`fixed inset-0 z-40 ${open ? "" : "pointer-events-none"}`}>
    <div onClick={onClose} className={`absolute inset-0 bg-zinc-950/50 backdrop-blur-sm transition-opacity duration-300 ${open ? "opacity-100" : "opacity-0"}`} />
    <aside className={`absolute right-0 top-0 flex h-full w-full max-w-md flex-col border-l border-zinc-200 bg-white shadow-2xl transition-transform duration-500 dark:border-zinc-800 dark:bg-zinc-950 ${open ? "translate-x-0" : "translate-x-full"}`}>
      <div className="flex items-center justify-between border-b border-zinc-200 px-6 py-5 dark:border-zinc-800"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-500">Your order</p><h2 className="mt-1 text-2xl font-black">Cart <span className="text-zinc-400">({items.reduce((sum, [, quantity]) => sum + quantity, 0)})</span></h2></div><button onClick={onClose} className="rounded-full p-2 text-zinc-500 transition hover:bg-zinc-100 hover:text-zinc-950 dark:hover:bg-zinc-800 dark:hover:text-white"><X size={20} /></button></div>
      <div className="flex-1 overflow-y-auto px-6 py-5">{items.length === 0 ? <div className="flex flex-col items-center justify-center py-24 text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-3xl bg-orange-500/10 text-orange-500"><ShoppingBasket size={30} /></div><p className="font-black">Your cart is waiting</p><p className="mt-2 max-w-xs text-sm leading-6 text-zinc-500">Add a favorite and it will stay here even when you refresh the page.</p></div> : <div className="space-y-4">{items.map(([id, quantity], index) => { const product = products.find((item) => item.id === Number(id)); if (!product) return null; const title = product.title || product.name; return <div key={id} className="animate-fade-up flex gap-3 rounded-2xl border border-zinc-200 p-3 dark:border-zinc-800" style={{ animationDelay: `${index * 60}ms` }}><img src={product.image} alt={title} className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="truncate font-bold">{title}</p><p className="mt-1 text-xs text-orange-500">Rs. {Number(product.price * quantity).toLocaleString()}</p><div className="mt-3"><QtyStepper qty={quantity} onAdd={() => onAdd(product.id)} onRemove={() => onRemove(product.id)} /></div></div></div>; })}</div>}</div>
      {items.length > 0 && <div className="border-t border-zinc-200 px-6 py-5 dark:border-zinc-800"><div className="mb-4 flex items-center gap-2 rounded-xl bg-emerald-500/10 px-3 py-2.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400"><Clock3 size={15} />Estimated delivery: 25–35 minutes</div><div className="mb-4 flex items-center justify-between"><span className="text-sm text-zinc-500">Subtotal</span><span className="text-2xl font-black text-orange-500">Rs. {Number(total).toLocaleString()}</span></div><button onClick={() => { onCheckout(); onClose(); }} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-orange-500 py-4 font-black text-white shadow-xl shadow-orange-500/20 transition hover:-translate-y-0.5 hover:bg-orange-400"><Sparkles size={17} />Continue to checkout</button></div>}
    </aside>
  </div>;
}

export default CartDrawer;
