import { useMemo, useState } from "react";
import { Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { getAverageRating } from "../data/Product-Rating";
import ProductCard from "./ProductCard";

function MenuPage({ products = [], cart, onAdd, onRemove, initialCategory, onOpenDetail }) {
  const [category, setCategory] = useState(initialCategory || "All");
  const [rating, setRating] = useState(0);
  const [maxPrice, setMaxPrice] = useState(2000);
  const [query, setQuery] = useState("");
  const categories = ["All", ...new Set(products.map((product) => product.category).filter(Boolean))];
  const visible = useMemo(() => products.filter((product) => {
    const title = product.title || product.name || "";
    const matchesCategory = category === "All" || product.category === category;
    const matchesPrice = Number(product.price || 0) <= maxPrice;
    const matchesRating = !rating || getAverageRating(product.id) >= rating;
    const matchesQuery = `${title} ${product.description || ""}`.toLowerCase().includes(query.toLowerCase());
    return matchesCategory && matchesPrice && matchesRating && matchesQuery;
  }), [products, category, maxPrice, rating, query]);

  return <div className="min-h-[70vh] px-5 pb-20 pt-10 sm:px-8 md:px-10"><div className="mx-auto max-w-7xl"><div className="animate-fade-up flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-500">The menu</p><h1 className="mt-2 text-4xl font-black tracking-tight text-zinc-950 dark:text-white sm:text-5xl">Pick your next favorite.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">Fresh, generous and made for the moment. Find something delicious, then make it yours.</p></div><div className="flex items-center gap-2 rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><Filter size={17} className="text-orange-500" /><span className="text-sm font-bold">{visible.length} items</span></div></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-[230px_1fr]"><aside className="h-fit rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 lg:sticky lg:top-24"><div className="mb-5 flex items-center justify-between"><p className="flex items-center gap-2 font-black"><SlidersHorizontal size={17} className="text-orange-500" />Filters</p><button onClick={() => { setCategory("All"); setRating(0); setMaxPrice(2000); setQuery(""); }} className="text-xs font-bold text-orange-500">Reset</button></div><label className="relative block"><Search size={16} className="absolute left-3 top-3 text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search dishes" className="w-full rounded-xl border border-zinc-200 bg-zinc-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-orange-500 dark:border-zinc-700 dark:bg-zinc-950" /></label><div className="mt-6"><p className="mb-3 text-xs font-black uppercase tracking-wider text-zinc-400">Category</p><div className="flex flex-wrap gap-2 lg:flex-col">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-3 py-2 text-left text-sm font-bold transition ${category === item ? "bg-orange-500 text-white" : "text-zinc-500 hover:bg-orange-500/10 hover:text-orange-500"}`}>{item}</button>)}</div></div><div className="mt-6"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">Max price</p><span className="text-xs font-black text-orange-500">Rs. {maxPrice}</span></div><input type="range" min="0" max="2000" step="50" value={maxPrice} onChange={(event) => setMaxPrice(Number(event.target.value))} className="w-full accent-orange-500" /></div><div className="mt-6"><p className="mb-3 text-xs font-black uppercase tracking-wider text-zinc-400">Rating</p><div className="flex gap-2">{[0, 4, 4.5].map((value) => <button key={value} onClick={() => setRating(value)} className={`rounded-lg px-2.5 py-2 text-xs font-bold ${rating === value ? "bg-zinc-900 text-white dark:bg-white dark:text-zinc-900" : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800"}`}>{value ? `${value}+` : "Any"}</button>)}</div></div></aside>
      <main><div className="mb-5 flex items-center justify-between"><p className="text-sm text-zinc-500">Showing <span className="font-bold text-zinc-900 dark:text-white">{visible.length}</span> delicious options</p>{(query || category !== "All" || rating > 0 || maxPrice < 2000) && <button onClick={() => { setCategory("All"); setRating(0); setMaxPrice(2000); setQuery(""); }} className="inline-flex items-center gap-1 text-xs font-bold text-orange-500">Clear filters <X size={14} /></button>}</div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map((product, index) => <div key={product.id} className="animate-fade-up" style={{ animationDelay: `${Math.min(index, 8) * 45}ms` }}><ProductCard product={product} qty={cart[product.id] || 0} onAdd={() => onAdd(product.id)} onRemove={() => onRemove(product.id)} onOpenDetail={onOpenDetail} /></div>)}</div>{!visible.length && <div className="rounded-3xl border border-dashed border-zinc-300 p-14 text-center dark:border-zinc-700"><p className="font-black">No dishes match that craving.</p><p className="mt-2 text-sm text-zinc-500">Try clearing a filter or searching for something else.</p></div>}</main></div></div></div>;
}

export default MenuPage;
